[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$RecipePath,
    [switch]$NoStudio,
    [switch]$PackageOnly,
    [ValidateRange(0, [long]::MaxValue)]
    [long]$UniverseId = 0,
    [ValidateRange(0, [long]::MaxValue)]
    [long]$PlaceId = 0
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$root = Split-Path -Parent $PSScriptRoot
$recipe = Get-Content -LiteralPath $RecipePath -Raw -Encoding UTF8 | ConvertFrom-Json
$preset = [string]$recipe.preset
if ($preset -notmatch '^[a-z][a-z0-9_-]{0,39}$') {
    throw "Preset names must use lowercase letters, numbers, underscores, or hyphens."
}
$presetSource = Join-Path $root "src/ui/presets/$preset"
foreach ($requiredModel in @("TemplateUI.model.json", "TemplateLoading.model.json", "StarterSignUI.model.json")) {
    if (-not (Test-Path -LiteralPath (Join-Path $presetSource $requiredModel) -PathType Leaf)) {
        throw "Preset '$preset' is missing $requiredModel."
    }
}

$currencies = @($recipe.currencies)
if ($currencies.Count -lt 1 -or $currencies.Count -gt 5) {
    throw "Choose between one and five currencies."
}

$usedIds = @{}
foreach ($currency in $currencies) {
    $id = [string]$currency.id
    if ($id -notmatch '^[a-z][a-z0-9_]{0,23}$') {
        throw "Currency ID '$id' must use lowercase letters, numbers, or underscores."
    }
    if ($usedIds.ContainsKey($id)) {
        throw "Currency ID '$id' is duplicated."
    }
    $usedIds[$id] = $true
}

$generated = Join-Path $root "build/designer/$preset"
$exports = Join-Path $root "exports"
New-Item -ItemType Directory -Path $generated, $exports -Force | Out-Null

# ConvertTo-Json escapes non-ASCII text as \uXXXX in Windows PowerShell.
# That is valid JSON but not a valid Luau string escape, so emit UTF-8 and
# escape only characters Luau requires.
function ConvertTo-LuauString([string]$Value) {
    $builder = [System.Text.StringBuilder]::new()
    [void]$builder.Append('"')
    foreach ($char in $Value.ToCharArray()) {
        if ($char -eq '"') {
            [void]$builder.Append('\"')
        } elseif ($char -eq '\') {
            [void]$builder.Append('\\')
        } elseif ([char]::IsControl($char)) {
            [void]$builder.Append('\' + [string][int]$char)
        } else {
            [void]$builder.Append($char)
        }
    }
    [void]$builder.Append('"')
    return $builder.ToString()
}

function Limit-Number([int64]$Value, [int64]$Minimum, [int64]$Maximum) {
    if ($Value -lt $Minimum) { return $Minimum }
    if ($Value -gt $Maximum) { return $Maximum }
    return $Value
}

function ConvertTo-DataNamespace([string]$Value) {
    $slug = $Value.ToLowerInvariant() -replace '[^a-z0-9_]+', '_'
    $slug = $slug.Trim('_')
    if ($slug -notmatch '^[a-z]') { $slug = "preset_$slug" }
    if ($slug.Length -le 15) { return $slug }

    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($slug)
        $suffix = ([System.BitConverter]::ToString($sha.ComputeHash($bytes))).Replace('-', '').Substring(0, 4).ToLowerInvariant()
    }
    finally {
        $sha.Dispose()
    }
    return "$($slug.Substring(0, 10))_$suffix"
}

$requestedNamespace = if ($recipe.PSObject.Properties.Name -contains "dataNamespace") {
    [string]$recipe.dataNamespace
} else {
    $preset
}
$dataNamespace = ConvertTo-DataNamespace $requestedNamespace

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("--!strict")
$lines.Add("")
$lines.Add("-- Generated by 5_GAME_DESIGNER.cmd. Safe to delete and rebuild.")
$lines.Add("return {")
$lines.Add("`texperienceMode = `"playable`",")
$lines.Add("`tpreset = $(ConvertTo-LuauString $preset),")
$lines.Add("`tdataNamespace = $(ConvertTo-LuauString $dataNamespace),")
$lines.Add("`tidentity = { universeId = $UniverseId, placeId = $PlaceId },")
$lines.Add("`tcurrencies = {")
foreach ($currency in $currencies) {
    $name = [string]$currency.name
    $symbol = [string]$currency.symbol
    $starting = Limit-Number ([int64]$currency.startingAmount) 0 1000000000000
    $color = @($currency.color)
    if ($color.Count -ne 3) { $color = @(255, 202, 10) }
    $red = Limit-Number ([int]$color[0]) 0 255
    $green = Limit-Number ([int]$color[1]) 0 255
    $blue = Limit-Number ([int]$color[2]) 0 255
    $lines.Add("`t`t{ id = $(ConvertTo-LuauString ([string]$currency.id)), name = $(ConvertTo-LuauString $name), symbol = $(ConvertTo-LuauString $symbol), color = { $red, $green, $blue }, startingAmount = $starting },")
}
$lines.Add("`t},")
$lines.Add("`tfeatures = {")
foreach ($property in $recipe.features.PSObject.Properties) {
    $enabled = if ([bool]$property.Value) { "true" } else { "false" }
    $lines.Add("`t`t$($property.Name) = $enabled,")
}
$lines.Add("`t},")
$lines.Add("}")

$sharedCopy = Join-Path $generated "shared"
New-Item -ItemType Directory -Path $sharedCopy -Force | Out-Null
Copy-Item -Path (Join-Path $root "src/shared/*") -Destination $sharedCopy -Recurse -Force
$configPath = Join-Path $sharedCopy "DesignerConfig.luau"
[System.IO.File]::WriteAllLines($configPath, $lines, [System.Text.UTF8Encoding]::new($false))

& lune run (Join-Path $root "scripts/validate-designer-config.luau") $configPath
if ($LASTEXITCODE -ne 0) { throw "Generated DesignerConfig.luau failed validation." }

function Update-ProjectPaths($Node) {
    if ($null -eq $Node -or $Node -is [string] -or $Node -is [ValueType]) { return }
    if ($Node -is [System.Collections.IEnumerable] -and $Node -isnot [System.Management.Automation.PSCustomObject]) {
        foreach ($item in $Node) { Update-ProjectPaths $item }
        return
    }
    foreach ($property in @($Node.PSObject.Properties)) {
        if ($property.Name -eq '$path' -and $property.Value -is [string]) {
            $property.Value = "../../../$($property.Value -replace '\\', '/')"
        } else {
            Update-ProjectPaths $property.Value
        }
    }
}

$presetRoot = "../../../src/ui/presets/$preset"
$project = Get-Content -LiteralPath (Join-Path $root "default.project.json") -Raw -Encoding UTF8 | ConvertFrom-Json
$project.name = "Generated_$preset"
Update-ProjectPaths $project.tree
if ($PlaceId -gt 0) {
    $project | Add-Member -MemberType NoteProperty -Name servePlaceIds -Value @($PlaceId) -Force
}
$project.tree.ReplicatedStorage.Template.Shared.'$path' = "shared"
$project.tree.StarterGui | Add-Member -MemberType NoteProperty -Name TemplateUI -Value ([pscustomobject]@{ '$path' = "$presetRoot/TemplateUI.model.json" }) -Force
$project.tree.StarterGui | Add-Member -MemberType NoteProperty -Name TemplateLoading -Value ([pscustomobject]@{ '$path' = "$presetRoot/TemplateLoading.model.json" }) -Force
$project.tree.StarterGui | Add-Member -MemberType NoteProperty -Name StarterSignUI -Value ([pscustomobject]@{ '$path' = "$presetRoot/StarterSignUI.model.json" }) -Force
$projectPath = Join-Path $generated "SelectedExperience.project.json"
$utf8 = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($projectPath, ($project | ConvertTo-Json -Depth 12), $utf8)

$packageProject = @{
    name = "UI_$preset"
    tree = @{
        '$path' = "$presetRoot/TemplateUI.model.json"
        PackagePreview = @{ '$path' = "../../../ui-packages/PackagePreview.client.luau" }
    }
}
$packageProjectPath = Join-Path $generated "SelectedPackage.project.json"
[System.IO.File]::WriteAllText($packageProjectPath, ($packageProject | ConvertTo-Json -Depth 8), $utf8)

$safePreset = if ($preset -eq "rpg") {
    "RPG"
} else {
    (Get-Culture).TextInfo.ToTitleCase(($preset -replace '[-_]+', ' ')) -replace ' ', ''
}
$packageOutput = Join-Path $exports "UI_$safePreset.rbxm"
& rojo build $packageProjectPath --output $packageOutput
if ($LASTEXITCODE -ne 0) { throw "Rojo could not build the selected UI package." }

if (-not $PackageOnly) {
    $placeOutput = Join-Path $exports "Playable_$safePreset.rbxlx"
    & rojo build $projectPath --output $placeOutput
    if ($LASTEXITCODE -ne 0) { throw "Rojo could not build the selected test experience." }

    if (-not $NoStudio) {
        $studio = Get-ChildItem "$env:LOCALAPPDATA\Roblox\Versions" -Filter RobloxStudioBeta.exe -File -Recurse |
            Sort-Object LastWriteTime -Descending |
            Select-Object -First 1
        if (-not $studio) { throw "Roblox Studio is not installed." }
        Start-Process -FilePath $studio.FullName -ArgumentList ('"{0}"' -f $placeOutput)
    }
    Write-Host "Playable test: $placeOutput" -ForegroundColor Green
}

Write-Host "UI package: $packageOutput" -ForegroundColor Green
